### ISSUE TITLE
Error: The type 'DiagnosticableMixin' can't be mixed in. class DateTimePickerTheme with DiagnosticableMixin

### ISSUE THREAD

**Issue by MarkBurt** [dylanwuzh/flutter-cupertino-date-picker#135]
Flutter 1.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 8874f21e79 (9 days ago) • 2020-10-29 14:14:35 -0700
Engine • revision a1440ca392
Tools • Dart 2.10.3

The following problems occur after import:
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_cupertino_date_picker-1.0.26+2/lib/src/date_picker_theme.dart:23:32: Error: Type 'DiagnosticableMixin' not found.
class DateTimePickerTheme with DiagnosticableMixin {
                               ^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.flutter-io.cn/flutter_cupertino_date_picker-1.0.26+2/lib/src/date_picker_theme.dart:23:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class DateTimePickerTheme with DiagnosticableMixin {

The solution is:
Removed ‘with DiagnosticableMixin’ or change 'DiagnosticableMixin' to 'Diagnosticable' and it work well for me.

**Comment by cxjwin** [comment]
same problem

**Comment by wisnuwijo** [comment]
same problem

**Comment by wisnuwijo** [comment]
> The solution is:
> Removed ‘with DiagnosticableMixin’ or change 'DiagnosticableMixin' to 'Diagnosticable' and it work well for me.

The solution is:
Removed ‘with DiagnosticableMixin’ or change 'DiagnosticableMixin' to 'Diagnosticable' and it work well for me.

**Comment by BringTheChill** [comment]
remove it from where?

**Comment by Marcosmaliki** [comment]
Why is this closed

**Comment by HysonHou** [comment]
Why is this closed
