### ISSUE TITLE
Build error with Flutter beta channel,  No named parameter with the name 'shadowThemeOnly'.

### ISSUE THREAD

**Issue by jerry-cai** [dylanwuzh/flutter-cupertino-date-picker#138]
../../development/flutter/.pub-cache/git/flutter-cupertino-date-picker-38630701b92a4fd0b753f9ab38b3581a5645a629/lib/src/date_picker.dart:103:34: Error: No named parameter with the name 'shadowThemeOnly'.
        theme: Theme.of(context, shadowThemeOnly: true),
                                 ^^^^^^^^^^^^^^^
../../development/flutter/packages/flutter/lib/src/material/theme.dart:107:20: Context: Found this candidate, but the arguments don't match.
  static ThemeData of(BuildContext context) {
                   ^^

Command PhaseScriptExecution failed with a nonzero exit code

**Comment by yashrajsharma23** [comment]
I am also facing the same issue if you found the solution please share it.
