### ISSUE TITLE
Add (numeric) keyboard support for the TimePicker

### ISSUE THREAD

**Issue by robinbonnes** [dylanwuzh/flutter-cupertino-date-picker#64]
We use the TimePicker a lot. It would be great if it could support numeric keyboard input to type a specific HH:mm time faster.

Example:

![image](https://user-images.githubusercontent.com/5117166/68739230-a232a100-05e8-11ea-9c2b-92ebae5f67bb.png)

I also requested this for the Cupertino Datepicker from Flutter, however they are not going to implement it because its not a specific iOS (Cupertino) feature. See: @https://github.com/flutter/flutter/issues/28633

Maybe this is something you want to implement?

**Comment by dylanwuzh** [comment]
This requirement is very uncommon and will not be considered for support for now
