### ISSUE TITLE
i18n support for date and time Numbers ie Arabic and Farsi numbers

### ISSUE THREAD

**Issue by shadyshrif** [dylanwuzh/flutter-cupertino-date-picker#80]
The _StringsI18n  class contains translation for the weeks and the month's names **only**.
Some languages like Arabic and Farsi require i18n for the numbers itself.

To get the idea, these are the numbers in English, Farsi, and Arabic

english = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
farsi = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
arabic = ['۰', '۱', '۲', '۳', '٦', '٥', '٤', '۷', '۸', '۹'];

You can find all available languages here https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system#Glyph_comparison

How to allow that in _StringsI18n  ?

**Comment by dylanwuzh** [comment]
Already support arabic language. You can add Farsi language like this: [add-more-language](https://github.com/dylanwuzh/flutter-cupertino-date-picker#add-more-language)
