### ISSUE TITLE
Error: The type 'Diagnosticable' can't be used as supertype.

### ISSUE THREAD

**Issue by wasabia** [dylanwuzh/flutter-cupertino-date-picker#85]
```
Compiler message:
../../.pub-cache/hosted/pub.flutter-io.cn/flutter_cupertino_date_picker-1.0.12/lib/src/date_picker_theme.dart:23:7: Error: The type 'Diagnosticable' can't be used as supertype.
class DateTimePickerTheme extends Diagnosticable {
```

Flutter 1.15.22-pre.21
flutter-cupertino-date-picker 1.0.12

**Comment by wasabia** [comment]
https://github.com/flutter/flutter/pull/51495

**Comment by rignaneseleo** [comment]
any fix?

**Comment by wasabia** [comment]
@rignaneseleo  replace extends to  with

**Comment by rignaneseleo** [comment]
I solved it using Flutter (Channel dev, v1.15.20) instead of Flutter (Channel dev, v1.15.21).

**Comment by ukieTux** [comment]
Fix it by change extends to with

like this  https://github.com/junqi/flutter_datetime_picker/commit/561f98fdcc5f210fb81cc45db5925df3b0c23d2d

**Comment by ukieTux** [comment]
or you can change it manually 
.pub-cache/hosted/pub.dartlang.org/flutter_cupertino_date_picker-1.0.12/lib/src/date_picker_theme.dart

find 
`class DatePickerTheme extends Diagnosticable `
then replace with 
`class DatePickerTheme with DiagnosticableMixin`

**Comment by rignaneseleo** [comment]
what should I put in my pubspec then?

**Comment by ukieTux** [comment]
just use this library, then you can edit manually in $flutter_home/.pub-cache/hosted/pub.dartlang.org/flutter_cupertino_date_picker-1.0.12/lib/src/date_picker_theme.dart

**Comment by ukieTux** [comment]
or you can direct to path in error message

**Comment by rignaneseleo** [comment]
Yes, but I'd like to use a better solution since I'm going to deploy using codemagic and .pub-cache is ignored from github.

**Comment by dylanwuzh** [comment]
Please update `1.0.13` version and try. Modified `DatePickerTheme`:
```
class DateTimePickerTheme with DiagnosticableMixin
```
