### ISSUE TITLE
更新最新flutter后会报错

### ISSUE THREAD

**Issue by 403605209** [dylanwuzh/flutter-cupertino-date-picker#88]
Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
      const DateTimePickerTheme({
            ^^^^^^^^^^^^^^^^^^^
    Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
    build failed.

**Comment by liketemple** [comment]
meet the same problem

**Comment by liketemple** [comment]
lib/src/date_picker_theme.dart:39:9: Error: The superclass, 'Diagnosticable', has no unnamed constructor that takes no arguments.
  const DateTimePickerTheme({
        ^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

**Comment by liketemple** [comment]
- class DateTimePickerTheme extends Diagnosticable
+ class DateTimePickerTheme with Diagnosticable
works

**Comment by rignaneseleo** [comment]
please @dylanwuzh update the library with this fix

**Comment by X287210480X** [comment]
> * class DateTimePickerTheme extends Diagnosticable
> 
> * class DateTimePickerTheme with Diagnosticable
>   works

good

**Comment by dylanwuzh** [comment]
更新了 `1.0.13` 版本，对 `DateTimePickerTheme` 进行了修改：`class DateTimePickerTheme with DiagnosticableMixin`，兼容Flutter的 `stable` channel
Updated `1.0.13` version, modified `DateTimePickerTheme`: `class DateTimePickerTheme with DiagnosticableMixin`, compatible with Flutter `stable` channel
