### ISSUE TITLE
datetime 无法显示年月日

### ISSUE THREAD

**Issue by xujie198705292135** [dylanwuzh/flutter-cupertino-date-picker#91]
![image](https://user-images.githubusercontent.com/5031418/79864635-52b09680-840c-11ea-8e78-c7120a3314a9.png)

**Comment by gracezgy** [comment]
遇到了同样的问题

**Comment by huanyueyaoqin** [comment]
`DateTimePickerMode.datetime`模式遇到同样的问题
Flutter 1.12.13+hotfix.9
Tools • Dart 2.7.2

**Comment by lwei1992** [comment]
遇到同样问题，datetime模式下，format改为‘yy-MM-dd HH:mm’就可以显示，但是年月日有显示也是错误的显示数值

**Comment by dylanwuzh** [comment]
升级到 `1.0.13+1` 版本试一下
