### ISSUE TITLE
Failed assertion: boolean expression must not be null

### ISSUE THREAD

**Issue by Zersya** [dylanwuzh/flutter-cupertino-date-picker#95]
Hi, I got an error when I pick the date, it only appears until April, and this error is showing up.

![image](https://user-images.githubusercontent.com/11307389/80562184-28b13280-8a11-11ea-959c-e2069cb69266.png)

Flutter doctor
```

[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E287, locale en-ID)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] VS Code (version 1.42.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by Zersya** [comment]
I change to **flutter_cupertino_date_picker: 1.0.15+1** and it's work now.

**Comment by collieryroad** [comment]
It seems it now needs .onMonthChangeStartWithFirstDate (dynamic var) - if you set this to true error goes - line 289 in date_picker_widget.dart  - also there is a print statement at line 350 that debug print min and max dates

**Comment by Zersya** [comment]
thank you, I set it `onMonthChangeStartWithFirstDate: true` and now it work without any error.
